import requests
import re
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen

# extract links from a page, credit: https://pythonspot.com/extract-links-from-webpage-beautifulsoup/
# I had to <pip3 install lxml> to get this to work
def getLinks(url):
    html_page = urlopen(url)
    soup = BeautifulSoup(html_page, features="lxml")
    links = []

    for link in soup.findAll('a', attrs={'href': re.compile("^/Movie Scripts/")}):
        links.append(link.get('href'))

    return links

# this page is a list of all the movies IMSDb has on file for the Sci-Fi genre
print( getLinks("https://imsdb.com/genre/Sci-Fi") )

# Now, we need to wade through list of links generated by getLinks and extract
# the urls for just the scripts, like is down below:

# this is just the script of a movie
URL = "https://imsdb.com/scripts/12-Monkeys.html"
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")
script = soup.find('pre')

# print(script.text.strip())
